server:
  port: 8011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/sb_proj_2023_t
    username: root
    password: 
mybatis:
  type-aliases-package: com.myk.exam.demo.vo
  